### ISSUE TITLE
cprMath.py fails to properly decode lattitude and longitude data given even and odd CPR formats

### ISSUE THREAD

**Issue by ThreeSixes** [ThreeSixes/airSuck#1]
There's some sort of issue with the algorithm that prevents the software from properly decoding CPR positioning data. I'm currently testing the library with cprTest.py

**Comment by tbessler** [comment]
I changed the input parameter from 1 to 0 (for Even vs Odd) in the second/problematic set of parameters, and it yielded the longitude you expected (and ostensibly the latitude as well), just off the coast of FL Keys.  cprMath.py needs some of the magic numbers changed into constants and explained, cuz it's a little tricky to figure out why they are what they are.

**Comment by ThreeSixes** [comment]
Excellent, I'll have to figure out why the 1/0 swap did that. Also, regarding the "magic numbers" - they're computed in real time because as we add support for surface-based CPR positioning (the reason I've included the 'surface' argument). When it's set to true the number will be 90.0 instead of 360.0. As for the name "magicNumber" - I just called it that becasue I had no clue what else to call it since there is no clear reference to what that value is called in the spec.

**Comment by ThreeSixes** [comment]
Here's some data from some tests I've run. I'll collect some more complete debugging data later tonight and post it here. For now I'm seeing an offset in the longitude data. Every aircraft seems to have this offset after being run through cprMath.decodeCPR() and I'm not sure why.

Epxected (from dump1090): 26.811859, -80.11645
Given: 26.811859130859375, -78.24514980973868

Expected(from dump1090): 26.54068, -80.013013
Given: 26.540679931640625, -78.51294155778555

**Comment by ThreeSixes** [comment]
Here's the extended debugging info for the expected position:

Expected lat/lon: 25.713226, -80.89447

cprMath.decodeCPR() yields: 31.668928760593218, -80.1545452249461
From this data: eLat 37426, eLon 113486, oLat 24928, oLon 11300, lastFmt 1

**Comment by ThreeSixes** [comment]
The reference I was using to determine the accuracy was buggy.
