### ISSUE TITLE
Name the Magic Numbers

### ISSUE THREAD

**Issue by tbessler** [ThreeSixes/airSuck#15]
cprMath.py contains a lot of magic numbers. Some of them look vaguely familiar to some of the source documentation in the comments (yay comments! GJ!), but not all (or maybe I need to read deeper). They should be assigned as constants, as some appear to be used more than once, which could cause significant problems if those values change, and also diminish readability/supportability of the code by non-SMEs.

**Comment by ThreeSixes** [comment]
I added some comments regarding the naming of the variables, and their purpose on issue #1 - we can rename it to whatever makes sense. I mainly named it that because I couldn't figure out what to call it. I'm all for making this much easier.

**Comment by ThreeSixes** [comment]
No more magic numbers.
